spring.application.name=iptv

# ----------------------------
# M3U - Playlist IPTV
# ----------------------------
app.m3u.host=http://SEU_HOST_AQUI
app.m3u.username=SEU_USUARIO
app.m3u.password=SUA_SENHA
app.m3u.cache-ttl-ms=300000

# ----------------------------
# TMDB - The Movie Database
# ----------------------------
app.tmdb.base-url=https://api.themoviedb.org/3
app.tmdb.api-key=SUA_CHAVE_TMDB
app.tmdb.language=pt-BR
app.tmdb.region=BR
app.epg.url=
app.cache.warmup.enabled=true

spring.codec.max-in-memory-size=100MB

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=SENHA_REDIS
cache.ttl.ms=300000

server.http2.enabled=true
server.compression.enabled=true
server.compression.min-response-size=1024
server.compression.mime-types=application/json,application/xml,text/plain,text/html,text/xml
server.compression.excluded-user-agents=
