/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSeriesRouteImport } from './routes/_authenticated/series'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMoviesRouteImport } from './routes/_authenticated/movies'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedSeriesBrowseRouteImport } from './routes/_authenticated/series.browse'
import { Route as AuthenticatedMoviesBrowseRouteImport } from './routes/_authenticated/movies.browse'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSeriesRoute = AuthenticatedSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMoviesRoute = AuthenticatedMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSeriesBrowseRoute =
  AuthenticatedSeriesBrowseRouteImport.update({
    id: '/browse',
    path: '/browse',
    getParentRoute: () => AuthenticatedSeriesRoute,
  } as any)
const AuthenticatedMoviesBrowseRoute =
  AuthenticatedMoviesBrowseRouteImport.update({
    id: '/browse',
    path: '/browse',
    getParentRoute: () => AuthenticatedMoviesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/movies': typeof AuthenticatedMoviesRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/series': typeof AuthenticatedSeriesRouteWithChildren
  '/movies/browse': typeof AuthenticatedMoviesBrowseRoute
  '/series/browse': typeof AuthenticatedSeriesBrowseRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/movies': typeof AuthenticatedMoviesRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/series': typeof AuthenticatedSeriesRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/movies/browse': typeof AuthenticatedMoviesBrowseRoute
  '/series/browse': typeof AuthenticatedSeriesBrowseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/movies': typeof AuthenticatedMoviesRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/series': typeof AuthenticatedSeriesRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/movies/browse': typeof AuthenticatedMoviesBrowseRoute
  '/_authenticated/series/browse': typeof AuthenticatedSeriesBrowseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/channels'
    | '/favorites'
    | '/history'
    | '/movies'
    | '/profile'
    | '/search'
    | '/series'
    | '/movies/browse'
    | '/series/browse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/channels'
    | '/favorites'
    | '/history'
    | '/movies'
    | '/profile'
    | '/search'
    | '/series'
    | '/'
    | '/movies/browse'
    | '/series/browse'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/channels'
    | '/_authenticated/favorites'
    | '/_authenticated/history'
    | '/_authenticated/movies'
    | '/_authenticated/profile'
    | '/_authenticated/search'
    | '/_authenticated/series'
    | '/_authenticated/'
    | '/_authenticated/movies/browse'
    | '/_authenticated/series/browse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/series': {
      id: '/_authenticated/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof AuthenticatedSeriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/movies': {
      id: '/_authenticated/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof AuthenticatedMoviesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/series/browse': {
      id: '/_authenticated/series/browse'
      path: '/browse'
      fullPath: '/series/browse'
      preLoaderRoute: typeof AuthenticatedSeriesBrowseRouteImport
      parentRoute: typeof AuthenticatedSeriesRoute
    }
    '/_authenticated/movies/browse': {
      id: '/_authenticated/movies/browse'
      path: '/browse'
      fullPath: '/movies/browse'
      preLoaderRoute: typeof AuthenticatedMoviesBrowseRouteImport
      parentRoute: typeof AuthenticatedMoviesRoute
    }
  }
}

interface AuthenticatedMoviesRouteChildren {
  AuthenticatedMoviesBrowseRoute: typeof AuthenticatedMoviesBrowseRoute
}

const AuthenticatedMoviesRouteChildren: AuthenticatedMoviesRouteChildren = {
  AuthenticatedMoviesBrowseRoute: AuthenticatedMoviesBrowseRoute,
}

const AuthenticatedMoviesRouteWithChildren =
  AuthenticatedMoviesRoute._addFileChildren(AuthenticatedMoviesRouteChildren)

interface AuthenticatedSeriesRouteChildren {
  AuthenticatedSeriesBrowseRoute: typeof AuthenticatedSeriesBrowseRoute
}

const AuthenticatedSeriesRouteChildren: AuthenticatedSeriesRouteChildren = {
  AuthenticatedSeriesBrowseRoute: AuthenticatedSeriesBrowseRoute,
}

const AuthenticatedSeriesRouteWithChildren =
  AuthenticatedSeriesRoute._addFileChildren(AuthenticatedSeriesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMoviesRoute: typeof AuthenticatedMoviesRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSeriesRoute: typeof AuthenticatedSeriesRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMoviesRoute: AuthenticatedMoviesRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSeriesRoute: AuthenticatedSeriesRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
